---
# https://gist.github.com/thikade/87f643ce8db86423fa7d245f7556a601
# mkdir -p ~/.config/yamllint/; cp ~/dotfiles/vim/yamllint_config.yml ~/.config/yamllint/config

rules:
  braces: enable
  brackets: enable
  colons: {max-spaces-before: 0, max-spaces-after: 8}
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values: enable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
